<?php
/**
 * Created by PhpStorm.
 * User: garbi
 * Date: 10.04.17
 * Time: 16:39
 */

// Supported Log Types
CONST SIGN_IN_OUT = 0;
CONST CREATE_USER = 1;
CONST DELETE_USER = 2;
CONST UPDATE_USER = 3;
CONST UPDATE_MEMBERSHIP = 4;
CONST CREATE_MEMBERSHIP = 5;
CONST UPDATE_MEMBERSHIP_VALIDITY = 6;
